theme: jekyll-theme-minimal
title: Welcome to izzykayu's github homepage.
description: Be on the look out for data visualizations, predictive models, emoji sentiment analysis, and more fun stuff!

plugins:
  - jekyll-github-metadata
  - jemoji
  - jekyll-gist
  - jekyll-mentions
