theme: jekyll-theme-minimal
title: Welcome to izzykayu's github homepage
description: Be on the look out for data visualizations, predictive models, social media analysis, mortality risk prediction, emoji sentiment analysis, and more fun stuff!

plugins:
  - jemoji
 
 plugins:
  - jekyll-mentions
