theme: jekyll-theme-minimal
title: Welcome to izzykayu's github homepage.
description: Be on the look out for data visualizations, predictive models, emoji sentiment analysis, and more fun stuff!


![IMAGE](dora.jpg)
**Me and Doraemon**

